[server]
enableCORS = false
enableXsrfProtection = false
headless = true

[client]
showErrorDetails = true
toolbarMode = "auto"

[theme]
base = "light"
primaryColor = "#0484fc"
backgroundColor = "#e4f5ff"
secondaryBackgroundColor = "#ffffff"
textColor = "#0b1220"
font = "sans serif"